# Generated by Django 4.1 on 2022-08-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='insession',
        ),
        migrations.AlterField(
            model_name='roommember',
            name='room_name',
            field=models.CharField(max_length=200),
        ),
    ]
