# Generated by Django 4.1 on 2022-08-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_roommember_insession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
