# Generated by Django 4.1 on 2022-08-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='extras',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='total_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
