# Generated by Django 4.1 on 2022-08-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_room_extras_room_total_users_room_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='votes',
        ),
    ]
