# Generated by Django 4.1 on 2022-08-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_room_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='room',
            name='total_users',
        ),
    ]
